openapi: 3.0.3
info:
  title: ADP APIs
  description: ADP API endpoints.
  version: 1.0.0
  contact: {}
  x-api-status-urls: false
  x-konfig-ignore:
    potential-incorrect-type: true
servers:
  - url: '{{service-root}}'
  - url: '{{security-token-service}}'
tags:
  - description: ''
    name: HR
  - description: ''
    name: Payroll
  - description: Request an OAuth Bearer Token
    name: Token Request
  - description: ''
    name: Core
  - description: ''
    name: Staffing
  - description: ''
    name: Talent
  - description: ''
    name: Time
paths:
  /hr/v2/workers:
    get:
      tags:
        - HR
      summary: Worker V2 (List with Top 5 and Prevent Cache)
      operationId: Hr_listTop5PreventCache
      description: Request a collection of the top 5 workers using a URI cache-buster.
      parameters:
        - name: $top
          in: query
          schema:
            type: string
            example: '5'
        - name: preventCache
          in: query
          schema:
            type: string
            example: TIMESTAMP
        - name: $filter
          in: query
          schema:
            type: string
            example: >-
              workers/workAssignments/homeOrganizationalUnits/typeCode/codeValue
              eq 'Department' and
              workers/workAssignments/homeOrganizationalUnits/nameCode/codeValue
              eq '001000'
      requestBody:
        content:
          application/octet-stream:
            schema:
              description: >-
                WARNING: Missing schema in media type object. Missing schema has
                been filled with this AnyType schema.
      responses:
        '200':
          description: ''
  /hr/v2/workers/{anthony-albright-aoid}:
    parameters:
      - name: anthony-albright-aoid
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - HR
      summary: Worker V2 (Single by AOID)
      operationId: Hr_getWorkerByAoid
      description: Request a single worker given their AOID.
      parameters:
        - name: preventCache
          in: query
          schema:
            type: string
            example: TIMESTAMP
      requestBody:
        content:
          application/octet-stream:
            schema:
              description: >-
                WARNING: Missing schema in media type object. Missing schema has
                been filled with this AnyType schema.
      responses:
        '200':
          description: ''
  /core/v1/operations/workerInformationManagement/hr.v2.workers/{key}:
    parameters:
      - name: key
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - HR
      summary: Worker V2 (Check Async Request Status)
      operationId: Hr_checkAsyncRequestStatus
      description: >-
        Check the status of an async request to the Worker API given the key
        returned as part of the original asyn response's "link" header.
      parameters:
        - name: $select
          in: query
          schema:
            type: string
            example: processingStatus
      requestBody:
        content:
          application/octet-stream:
            schema:
              description: >-
                WARNING: Missing schema in media type object. Missing schema has
                been filled with this AnyType schema.
      responses:
        '200':
          description: ''
  /hr/v2/worker-demographics:
    get:
      tags:
        - HR
      summary: Worker Demographics V2 (List with Top 5 and Prevent Cache)
      operationId: Hr_listTop5PreventCache
      description: >-
        Request demographic data for a collection of the top 5 workers using a
        URI cache-buster.
      parameters:
        - name: $top
          in: query
          schema:
            type: string
            example: '5'
        - name: preventCache
          in: query
          schema:
            type: string
            example: TIMESTAMP
        - name: $filter
          in: query
          schema:
            type: string
            example: >-
              workers/workAssignments/homeOrganizationalUnits/typeCode/codeValue
              eq 'Department' and
              workers/workAssignments/homeOrganizationalUnits/nameCode/codeValue
              eq '001000'
      requestBody:
        content:
          application/octet-stream:
            schema:
              description: >-
                WARNING: Missing schema in media type object. Missing schema has
                been filled with this AnyType schema.
      responses:
        '200':
          description: ''
  /hr/v2/worker-demographics/{anthony-albright-aoid}:
    parameters:
      - name: anthony-albright-aoid
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - HR
      summary: Worker Demographics V2 (Single by AOID)
      operationId: Hr_getWorkerDemographicsByAoid
      description: Request demographic data for a single worker given their AOID.
      parameters:
        - name: preventCache
          in: query
          schema:
            type: string
            example: TIMESTAMP
      requestBody:
        content:
          application/octet-stream:
            schema:
              description: >-
                WARNING: Missing schema in media type object. Missing schema has
                been filled with this AnyType schema.
      responses:
        '200':
          description: ''
  /payroll/v1/payroll-output:
    get:
      tags:
        - Payroll
      summary: Payroll Outputs V1 (List for Region / Company Code / Year / Week)
      operationId: Payroll_listPayrollOutputs
      description: >-
        Fetches a list of payroll outputs given a Region Code, Company Code,
        Year and Week.
      parameters:
        - name: $filter
          in: query
          schema:
            type: string
            example: >-
              payrollScheduleReference/payrollYear eq 2018 and
              payrollScheduleReference/payrollWeekNumber eq 10 and
              payrollGroupCode/codeValue eq %26Y%26 and
              payrollRegionCode/codeValue eq BALT
        - name: $count
          in: query
          schema:
            type: string
            example: 'true'
        - name: use-cache
          in: query
          schema:
            type: string
            example: 'false'
        - name: level
          in: query
          schema:
            type: string
            example: details
        - name: $select
          in: query
          schema:
            type: string
            example: >-
              earnings,reportableEarningsAndBenefits,reimbursements,statutoryDeductions,nonStatutoryDeductions,memos,configurationTags
      requestBody:
        content:
          application/octet-stream:
            schema:
              description: >-
                WARNING: Missing schema in media type object. Missing schema has
                been filled with this AnyType schema.
      responses:
        '200':
          description: ''
  /auth/oauth/v2/token:
    post:
      tags:
        - Token Request
      summary: Token Request (Authorization Header)
      operationId: TokenRequest_createWithAuthorizationHeader
      description: >-
        A request to get an OAuth bearer token for our demo ADP Workforce Now by
        adding an Authorization header containing the base-64 encoded
        credentials.
      parameters:
        - name: grant_type
          in: query
          schema:
            type: string
            example: client_credentials
        - name: client_id
          in: query
          schema:
            type: string
            example: '{{client-id}}'
        - name: client_secret
          in: query
          schema:
            type: string
            example: '{{client-secret}}'
      requestBody:
        content:
          application/octet-stream:
            schema:
              description: >-
                WARNING: Missing schema in media type object. Missing schema has
                been filled with this AnyType schema.
      responses:
        '200':
          description: ''
